[workspace]
default-members = ["exporter"]
members = ["models", "exporter"]

[workspace.dependencies]
sea-orm = { version = "0.11.3", default-features = false, features = [
    "runtime-tokio-native-tls",
    "macros",
    "with-chrono",
    "with-uuid",
    "sqlx-mysql",
] }
